name: GitHub Activity Updater

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  run_activity_updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0

      - name: Run activity updater
        run: |
          cargo run

      - name: Commit and push if changed
        run: |
          git config --global user.name 'Anirudh Konidala'
          git config --global user.email 'kidskodingclub@gmail.com'
          git pull --rebase
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update profile with latest repository activity"
          git push
