name: GitHub Activity Updater

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_activity_updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0

      - name: Run activity updater
        run: |
          cargo run
