name: GitHub Activity Updater

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  run_activity_updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0

      - name: Run activity updater
        run: |
          cargo run

      - name: Commit and push updated README
        run: |
          git add README.md
          git commit -m "Update README with latest GitHub activity"
          git push
